### ISSUE TITLE
[BUG] : Commande /add_temp_channel ne fonctionne pas

### ISSUE THREAD

**Issue by louis-ducruet** [louis-ducruet/Epsius-Discord-Bot#87]
### **Description du bug :**

Au lancement de la commande le serveur nous retourne une message d'erreur dans la console
```node
unhandledRejection : DiscordAPIError[50035]: Invalid Form Body
name[BASE_TYPE_REQUIRED]: This field is required
 Promise :
{
  promise: Promise {
    <rejected> DiscordAPIError[50035]: Invalid Form Body
    name[BASE_TYPE_REQUIRED]: This field is required
        at SequentialHandler.runRequest (C:\Users\LouisDucruet\Documents\EPSI\Bot\Epsius-Discord-Bot\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:287:15)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async SequentialHandler.queueRequest (C:\Users\LouisDucruet\Documents\EPSI\Bot\Epsius-Discord-Bot\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:99:14)
        at async REST.request (C:\Users\LouisDucruet\Documents\EPSI\Bot\Epsius-Discord-Bot\node_modules\@discordjs\rest\dist\lib\REST.cjs:52:22)
        at async GuildChannelManager.create (C:\Users\LouisDucruet\Documents\EPSI\Bot\Epsius-Discord-Bot\node_modules\discord.js\src\managers\GuildChannelManager.js:145:18) {
      rawError: [Object],
      code: 50035,
      status: 400,
      method: 'POST',
      url: 'https://discord.com/api/v10/guilds/961267363808944169/channels',
      requestBody: [Object]
    }
  }
}
```

### **Comment le reproduire**

Lancer la commande le bug se produit dans 100% des cas

### **Ce qui aurais du se produire**

Création d'un channel avec attribution de permissions

### **Capture d'écran**

![Capture d'écran](https://user-images.githubusercontent.com/92012383/184500904-82c52d69-41d9-494a-b158-bc3f3f274430.png)

### **Information sur la machine**

 - Type d'appareil: Tous
 - OS: Tous
 - Navigateur: Tous
 - Date et Heure: 13/08/2022 17h35

**Comment by louis-ducruet** [comment]
Le problème vient de interaction.guild.channels.create() qui provoque un crash car les paramètres ne corresponde pas à ce qui est attendu.
Hors il s'agit des paramètres de la docs pour ma phase de diagnostique : https://discord.js.org/#/docs/main/stable/class/GuildChannelManager?scrollTo=create

**Comment by louis-ducruet** [comment]
Mise en place d'un message de maintenance en attendant de trouver une solution

**Comment by louis-ducruet** [comment]
Après recherche approfondi il faut maintenant mettre le nom du channel avec les autres options contrairement à ce qui est mis sur la documentation
